### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by rubyFeedback** [rworkman/slackpkg#11]
Hey there,

Could a new release at https://github.com/rworkman/slackpkg/releases be issued when the new final slackware comes out?
Mostly for sync-reasing on non slackware distributions; I test various package managers
via some ruby scripts; see also related projects such as fpm
https://github.com/jordansissel/fpm/

**Comment by rworkman** [comment]
I'm not necessarily opposed to doing that, but I'll admit that I'm a bit wary - only because I already know that I won't keep up with that in the future. All releases have git tags associated with them, and packages of them are at https://slackpkg.org/stable/ -- is that sufficient for your needs?

**Comment by rworkman** [comment]
Re-open if needed/wanted.
