### ISSUE TITLE
New mirror brazil

### ISSUE THREAD

**Issue by slackjeff** [rworkman/slackpkg#14]
Hello Rob. I created a new mirror in Brazil, I manage the same. It was accepted after contact mirrors@slackware.com:
https://mirrors.slackware.com/mirrorlist/

The mirror is this: https://slackjeff.com.br/slackware/
I want to know if I can make a Pull request with this mirror in slackpkg or if this will be added to the future. thks!

**Comment by rworkman** [comment]
I am the person behind mirrors@slackware.com  so yes, I added the mirror there :-)
My email back to you bounced for some reason, but no worries.
Re adding the mirror to slackpkg config, I'd rather not do that -- I'd much prefer to not add any new mirrors to it, as the goal is for everyone to use the mirror redirect at mirrors.slackware.com

**Comment by slackjeff** [comment]
ok!!! obrigado!
