### ISSUE TITLE
Rebuilds package lists if missing

### ISSUE THREAD

**Issue by piterpunk** [rworkman/slackpkg#16]
If the package list is missing, Slackpkg ask the user to run `slackpkg update` and rebuild the list.

As the package list is a need to do anything useful with Slackpkg, the user always need to run the `slackpkg update`.

Would be nice if Slackpkg just rebuild the package list.

**Comment by rworkman** [comment]
Committed in ea08809a7510f1fafa1a5d818933c6cddffe5f69 ; thanks!  :-)
