### ISSUE TITLE
Can't overwrites all .new files in batch mode

### ISSUE THREAD

**Issue by piterpunk** [rworkman/slackpkg#19]
When in batch mode, or you put each file to be overwritten in `post-functions.conf` or just keep al them to look later.

Would be nice to able to overwrite all `.new` files and use the configuration for each file in `post-functions.conf` to be used for exceptions to the rule.

**Comment by rworkman** [comment]
Merged 9d5166d13bce28fee36327c1e00a66fcacb77025
