### ISSUE TITLE
:bulb: add DOWNLOADER variable to slackpkg.conf/slackpkg.conf.5

### ISSUE THREAD

**Issue by pete4abw** [rworkman/slackpkg#26]
I've been having issues with wget and noticed that there is a supported slackpkg variable **DOWNLOADER**.

`DOWNLOADER=curl` can be used along with `CURLFLAGS`.

This was noted in 2010 in the ChangeLog. Was it removed for some reason?

As for `WGETFLAGS` `--passive-ftp` is default behavior. Perhaps adding a `-w|--wait [seconds]` option may alleviate some timeout issues between connections?

Just a thought.

**Comment by pete4abw** [comment]
See PR #27 .

**Comment by piterpunk** [comment]
Closed by PR #27

**Comment by piterpunk** [comment]
Closed by PR #27

**Comment by piterpunk** [comment]
Closed by PR #27
