### ISSUE TITLE
slackpkg breaks when an essential commented line is removed from slackpkg.conf

### ISSUE THREAD

**Issue by tterpelle** [rworkman/slackpkg#29]
If you remove the following comment from `/etc/slackpkg/slackpkg.conf`, the `slackpkg` tool will cease to function:

```
# v15.0
```

```
root@darkstar:~# slackpkg info kernel-huge
expr: syntax error: missing argument after ‘length’

Your slackpkg.conf is outdated. Please, edit it using slackpkg.conf.new
as example or overwrite it with slackpkg.conf.new.

You can use 'slackpkg new-config' to do that.


root@darkstar:~# 
```

This seems to be cause by [line 163 in `/usr/libexec/slackpkg/core-functions.sh`](https://github.com/rworkman/slackpkg/blob/b211490ee56597c0c2417a9c40b0de2ec242de42/files/core-functions.sh#L163).

**Comment by piterpunk** [comment]
Well, this line should not be removed. I never thought someone would want to do that.

But I can understand what I guess is your use case: to have a configuration file without any comment. And it looks to be a valid one.

**Comment by saxa** [comment]
> Well, this line should not be removed. I never thought someone would want to do that.
Hi, but why the heck you try to put some essential things after a hash # in a bash ? What is the benefot of it ?
Would not be better just leave it with a very visible line like config_ver= or something similar ?
It seems very obvious to me that sooner or later somebody would remove it as it seems a commented line, therfore ignored by the 99.9% of bash scripts I believe.
Maybe a nice warning bofre like:
`# *** DO NOT REMOVE BELOW LINE ***`
`# v15.0 `

Sorry just out of curiousity.

**Comment by piterpunk** [comment]
> > Well, this line should not be removed. I never thought someone would want to do that.
> 
> Hi, but why the heck you try to put some essential things after a hash # in a bash ? What is the benefot of it ? 

As I wrote in my last comment, I just not thought someone would want to remove the line.

The enhancement by @tterpelle to provides `SLACKCFVERSION` explicitly in `slackpkg.conf` was just merged.

**Comment by saxa** [comment]
Yup I saw it, I personally ignore comment like bash :) but its still strange to me to know that some code could potentially depend on something that is commented. Anyway I saw the issue #30 which solves this. No worries.
