### ISSUE TITLE
Can't call new-config after slackpkg upgrades itself

### ISSUE THREAD

**Issue by piterpunk** [rworkman/slackpkg#7]
After upgrade there is a catch-22 situation:
```
root@bat:~# slackpkg update

Your slackpkg.conf is outdated. Please, edit it using slackpkg.conf.new
as example or overwrite it with slackpkg.conf.new.

You can use 'slackpkg new-config' to do that.


root@bat:~# slackpkg new-config

No CHECKSUMS.md5 found!  Please disable md5sums checking
on your /etc/slackpkg/slackpkg.conf or run slackpkg update
to download a new CHECKSUMS.md5 file.
```
The `slackpkg update` asks to use `slackpkg new-config` and `slackpkg new-config` to use `slackpkg update`.

As `new-config` doesn't need any of package lists, I guess it's good to add it to the commands that can be called with a not populated slackpkg's var directory.

**Comment by rworkman** [comment]
Fixed with 5edf86dcebd2ab55a4a7221db77e10676723bbb1 (merged #8)
