### ISSUE TITLE
Current64: Slackpkg 15.0 (no +) with CONF set fails to read the blacklist file

### ISSUE THREAD

**Issue by burdi01** [rworkman/slackpkg#9]
See https://www.linuxquestions.org/questions/slackware-14/slackpkg-2-84-0_beta1-testing-wanted-4175643527/page8.html#post6219515 for Dave's response.

However in https://github.com/rworkman/slackpkg/commit/9c2719ff0f0d99ad811fdd274fcdd8fc55b37488 I see a 'grep -v "^#" **$CONF**/blacklist | $MORECMD' ...

:D

**Comment by slackhead** [comment]
Please see https://www.linuxquestions.org/questions/slackware-14/current64-slackpkg-15-0-no-with-conf-set-fails-to-read-the-blacklist-file-4175690187/#post6219910

**Comment by rworkman** [comment]
This is fixed now, correct?

**Comment by rworkman** [comment]
Assuming it's fixed as I've not gotten any other reports; re-open if needed.
